### Linear Regression

In [1]:
from sklearn.linear_model import LinearRegression

In [5]:
x = [[1,1],[1,2],[2,2],[2,3]]
y = [2,3,3,4]
regressor = LinearRegression()
regressor.fit(x,y)
regressor.predict([[1,6]])

array([7.])

### Decision Trees

In [6]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
iris = load_iris()
x,y = iris.data,iris.target
clf = DecisionTreeClassifier()
clf.fit(x,y)
clf.predict([[5.0,3.0,4.0,2.0]])

array([2])

### Random Forest

In [7]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
x,y = make_classification(n_features=4,random_state=0)
clf = RandomForestClassifier(max_depth=2,random_state=0)
clf.fit(x,y)
clf.predict([[0,0,0,0]])

array([1])

### Support Vector Machines

In [9]:
from sklearn import svm
x = [[0,0],[1,1]]
y = [0,1]
clf = svm.SVC()
clf.fit(x,y)
clf.predict([[2.,2.]])

array([1])

### Neutral Networks

In [10]:
import tensorflow as tf

In [11]:
mnist = tf.keras.datasets.mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()
X_train, X_test = X_train / 255.0, X_test / 255.0
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])
predictions = model(X_train[:1]).numpy()
tf.nn.softmax(predictions).numpy()

11490434/11490434 [==============================] - 27s 2us/step


array([[0.15936522, 0.07698447, 0.05661316, 0.04018416, 0.13000539,
        0.07654897, 0.17020936, 0.08325151, 0.11159002, 0.09524765]],
      dtype=float32)